services:
  - type: web
    name: narodni-dom-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: ЗАГЛУШКА_ЗАМЕНИ_ПОТОМ
      - key: GEMINI_API_KEY
        value: ЗАГЛУШКА_ЗАМЕНИ_ПОТОМ
      - key: ADMIN_ID
        value: ЗАГЛУШКА_ЗАМЕНИ_ПОТОМ